
export const UPDATE_STATE="UPDATE_STATE"
export const ADD_TO_CART="ADD_TO_CART"
export const ADD_QUANTITY_OF_PRODUCT="ADD_QUANTITY_OF_PRODUCT"
export const REMOVE_QUANTITY_OF_PRODUCT="REMOVE_QUANTITY_OF_PRODUCT"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"